name: "Roam Research backup"

on:
  push:
    branches:
      - master
  schedule:
    -   cron: "0 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: checkout
        uses: actions/checkout@master
      #
      # - name: Change Directory
      #   run: |
      #       cd ~
      #       mkdir html_build
      #       # cd html_build

      - name: Generate HTML From Roam
        uses: dvargas92495/generate-roam-site-action@1.8.2
        with:
          roam_username: ${{ secrets.ROAMRESEARCH_USER }}
          roam_password: ${{ secrets.ROAMRESEARCH_PASSWORD }}
          roam_graph: ${{ secrets.ROAMRESEARCH_DATABASE }}
      - name: Commit changes
        uses: elstudio/actions-js-build/commit@v3
        with:
          commitMessage: Automated snapshot
